# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: carrito.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'carrito.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcarrito.proto\x12\x07\x63\x61rrito\"\x07\n\x05\x45mpty\"U\n\x08Producto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0e\n\x06nombre\x18\x02 \x01(\t\x12\x0e\n\x06precio\x18\x03 \x01(\x02\x12\r\n\x05stock\x18\x04 \x01(\x05\x12\x0e\n\x06imagen\x18\x05 \x01(\t\"6\n\x0eListaProductos\x12$\n\tproductos\x18\x01 \x03(\x0b\x32\x11.carrito.Producto\"T\n\rCompraRequest\x12\x13\n\x0bproducto_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63\x61ntidad\x18\x02 \x01(\x05\x12\x0f\n\x07tarjeta\x18\x03 \x01(\t\x12\x0b\n\x03nip\x18\x04 \x01(\t\"0\n\x0e\x43ompraResponse\x12\r\n\x05\x65xito\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2\x88\x01\n\x0e\x43\x61rritoService\x12:\n\x0fListarProductos\x12\x0e.carrito.Empty\x1a\x17.carrito.ListaProductos\x12:\n\x07\x43omprar\x12\x16.carrito.CompraRequest\x1a\x17.carrito.CompraResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'carrito_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=26
  _globals['_EMPTY']._serialized_end=33
  _globals['_PRODUCTO']._serialized_start=35
  _globals['_PRODUCTO']._serialized_end=120
  _globals['_LISTAPRODUCTOS']._serialized_start=122
  _globals['_LISTAPRODUCTOS']._serialized_end=176
  _globals['_COMPRAREQUEST']._serialized_start=178
  _globals['_COMPRAREQUEST']._serialized_end=262
  _globals['_COMPRARESPONSE']._serialized_start=264
  _globals['_COMPRARESPONSE']._serialized_end=312
  _globals['_CARRITOSERVICE']._serialized_start=315
  _globals['_CARRITOSERVICE']._serialized_end=451
# @@protoc_insertion_point(module_scope)
