# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import carrito_pb2 as carrito__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in carrito_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CarritoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarProductos = channel.unary_unary(
                '/carrito.CarritoService/ListarProductos',
                request_serializer=carrito__pb2.Empty.SerializeToString,
                response_deserializer=carrito__pb2.ListaProductos.FromString,
                _registered_method=True)
        self.Comprar = channel.unary_unary(
                '/carrito.CarritoService/Comprar',
                request_serializer=carrito__pb2.CompraRequest.SerializeToString,
                response_deserializer=carrito__pb2.CompraResponse.FromString,
                _registered_method=True)


class CarritoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Comprar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CarritoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProductos,
                    request_deserializer=carrito__pb2.Empty.FromString,
                    response_serializer=carrito__pb2.ListaProductos.SerializeToString,
            ),
            'Comprar': grpc.unary_unary_rpc_method_handler(
                    servicer.Comprar,
                    request_deserializer=carrito__pb2.CompraRequest.FromString,
                    response_serializer=carrito__pb2.CompraResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'carrito.CarritoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('carrito.CarritoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CarritoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carrito.CarritoService/ListarProductos',
            carrito__pb2.Empty.SerializeToString,
            carrito__pb2.ListaProductos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Comprar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/carrito.CarritoService/Comprar',
            carrito__pb2.CompraRequest.SerializeToString,
            carrito__pb2.CompraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
