services:
  mongo:
    image: mongo:7
    container_name: tienda_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  
  inventario:
    build: .
    container_name: tienda_inventario
    command: python inventario/servidor_inventario.py
    ports:
      - "50051:50051"
    environment:
      MONGO_URI: "mongodb://mongo:27017/rellenitos"
    volumes:
      - .:/app
    depends_on:
      - mongo
  
  pago:
    build: .
    container_name: tienda_pago
    command: python pago/servidor_pago.py
    ports:
      - "50053:50053"
    volumes:
      - .:/app

  carrito:
    build: .
    container_name: tienda_carrito
    command: python carrito/servidor_carrito.py
    ports:
      - "50055:50055"
    volumes:
      - .:/app
    depends_on:
      - inventario
      - pago

  web_backend:
    build: .
    container_name: tienda_web_backend
    command: uvicorn web_backend.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    env_file:
    - .env
    volumes:
      - .:/app
    environment:
      MONGO_URI: "mongodb://mongo:27017/rellenitos"
      MERCADO_PAGO_ACCESS_TOKEN: ${MERCADO_PAGO_ACCESS_TOKEN}
      PUBLIC_BASE_URL: "https://cried-hypnoses-frostbite.ngrok-free.dev"
    depends_on:
      - inventario
      - carrito
      - pago

volumes:
  mongo_data:


