# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import inventario_pb2 as inventario__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inventario_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InventarioServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListarProductos = channel.unary_unary(
                '/inventario.InventarioService/ListarProductos',
                request_serializer=inventario__pb2.Empty.SerializeToString,
                response_deserializer=inventario__pb2.ListaProductos.FromString,
                _registered_method=True)
        self.VerificarStock = channel.unary_unary(
                '/inventario.InventarioService/VerificarStock',
                request_serializer=inventario__pb2.ProductoRequest.SerializeToString,
                response_deserializer=inventario__pb2.StockResponse.FromString,
                _registered_method=True)
        self.DescontarStock = channel.unary_unary(
                '/inventario.InventarioService/DescontarStock',
                request_serializer=inventario__pb2.ProductoRequest.SerializeToString,
                response_deserializer=inventario__pb2.StockResponse.FromString,
                _registered_method=True)
        self.ActualizarStock = channel.unary_unary(
                '/inventario.InventarioService/ActualizarStock',
                request_serializer=inventario__pb2.ActualizarStockRequest.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)
        self.ActualizarPrecio = channel.unary_unary(
                '/inventario.InventarioService/ActualizarPrecio',
                request_serializer=inventario__pb2.ActualizarPrecioRequest.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)
        self.AgregarProducto = channel.unary_unary(
                '/inventario.InventarioService/AgregarProducto',
                request_serializer=inventario__pb2.NuevoProducto.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)
        self.EliminarProducto = channel.unary_unary(
                '/inventario.InventarioService/EliminarProducto',
                request_serializer=inventario__pb2.EliminarProductoRequest.SerializeToString,
                response_deserializer=inventario__pb2.Empty.FromString,
                _registered_method=True)
        self.ActualizarNombre = channel.unary_unary(
                '/inventario.InventarioService/ActualizarNombre',
                request_serializer=inventario__pb2.ActualizarNombreRequest.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)
        self.ActualizarImagen = channel.unary_unary(
                '/inventario.InventarioService/ActualizarImagen',
                request_serializer=inventario__pb2.ActualizarImagenRequest.SerializeToString,
                response_deserializer=inventario__pb2.Producto.FromString,
                _registered_method=True)


class InventarioServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListarProductos(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerificarStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DescontarStock(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarStock(self, request, context):
        """ADMIN
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarPrecio(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AgregarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EliminarProducto(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarNombre(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActualizarImagen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InventarioServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListarProductos': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarProductos,
                    request_deserializer=inventario__pb2.Empty.FromString,
                    response_serializer=inventario__pb2.ListaProductos.SerializeToString,
            ),
            'VerificarStock': grpc.unary_unary_rpc_method_handler(
                    servicer.VerificarStock,
                    request_deserializer=inventario__pb2.ProductoRequest.FromString,
                    response_serializer=inventario__pb2.StockResponse.SerializeToString,
            ),
            'DescontarStock': grpc.unary_unary_rpc_method_handler(
                    servicer.DescontarStock,
                    request_deserializer=inventario__pb2.ProductoRequest.FromString,
                    response_serializer=inventario__pb2.StockResponse.SerializeToString,
            ),
            'ActualizarStock': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarStock,
                    request_deserializer=inventario__pb2.ActualizarStockRequest.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
            'ActualizarPrecio': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarPrecio,
                    request_deserializer=inventario__pb2.ActualizarPrecioRequest.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
            'AgregarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.AgregarProducto,
                    request_deserializer=inventario__pb2.NuevoProducto.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
            'EliminarProducto': grpc.unary_unary_rpc_method_handler(
                    servicer.EliminarProducto,
                    request_deserializer=inventario__pb2.EliminarProductoRequest.FromString,
                    response_serializer=inventario__pb2.Empty.SerializeToString,
            ),
            'ActualizarNombre': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarNombre,
                    request_deserializer=inventario__pb2.ActualizarNombreRequest.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
            'ActualizarImagen': grpc.unary_unary_rpc_method_handler(
                    servicer.ActualizarImagen,
                    request_deserializer=inventario__pb2.ActualizarImagenRequest.FromString,
                    response_serializer=inventario__pb2.Producto.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'inventario.InventarioService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('inventario.InventarioService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InventarioService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListarProductos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ListarProductos',
            inventario__pb2.Empty.SerializeToString,
            inventario__pb2.ListaProductos.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerificarStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/VerificarStock',
            inventario__pb2.ProductoRequest.SerializeToString,
            inventario__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DescontarStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/DescontarStock',
            inventario__pb2.ProductoRequest.SerializeToString,
            inventario__pb2.StockResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarStock(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ActualizarStock',
            inventario__pb2.ActualizarStockRequest.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarPrecio(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ActualizarPrecio',
            inventario__pb2.ActualizarPrecioRequest.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AgregarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/AgregarProducto',
            inventario__pb2.NuevoProducto.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EliminarProducto(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/EliminarProducto',
            inventario__pb2.EliminarProductoRequest.SerializeToString,
            inventario__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarNombre(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ActualizarNombre',
            inventario__pb2.ActualizarNombreRequest.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActualizarImagen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/inventario.InventarioService/ActualizarImagen',
            inventario__pb2.ActualizarImagenRequest.SerializeToString,
            inventario__pb2.Producto.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
