# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import pago_pb2 as pago__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in pago_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PagoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcesarPago = channel.unary_unary(
                '/pago.PagoService/ProcesarPago',
                request_serializer=pago__pb2.PagoRequest.SerializeToString,
                response_deserializer=pago__pb2.PagoResponse.FromString,
                _registered_method=True)


class PagoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcesarPago(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PagoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcesarPago': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcesarPago,
                    request_deserializer=pago__pb2.PagoRequest.FromString,
                    response_serializer=pago__pb2.PagoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pago.PagoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pago.PagoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PagoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcesarPago(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pago.PagoService/ProcesarPago',
            pago__pb2.PagoRequest.SerializeToString,
            pago__pb2.PagoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
