# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pago.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'pago.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npago.proto\x12\x04pago\":\n\x0bPagoRequest\x12\r\n\x05total\x18\x01 \x01(\x02\x12\x0f\n\x07tarjeta\x18\x02 \x01(\t\x12\x0b\n\x03nip\x18\x03 \x01(\t\"1\n\x0cPagoResponse\x12\x10\n\x08\x61probado\x18\x01 \x01(\x08\x12\x0f\n\x07mensaje\x18\x02 \x01(\t2D\n\x0bPagoService\x12\x35\n\x0cProcesarPago\x12\x11.pago.PagoRequest\x1a\x12.pago.PagoResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pago_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PAGOREQUEST']._serialized_start=20
  _globals['_PAGOREQUEST']._serialized_end=78
  _globals['_PAGORESPONSE']._serialized_start=80
  _globals['_PAGORESPONSE']._serialized_end=129
  _globals['_PAGOSERVICE']._serialized_start=131
  _globals['_PAGOSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
